import jsPDF from "jspdf";
import { generateQRCode } from "./generateQRCode";

interface AdvocateBranding {
    name: string;
    enrollmentNumber: string;
    email: string;
    phone: string;
    chamberName?: string;
    website?: string;
    logoUrl?: string;
    signatureUrl?: string;
}

const loadImageAsBase64 = async (url: string): Promise<string> => {
    const response = await fetch(url);
    const blob = await response.blob();

    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
    });
};

export const generateCombinedLegalPDF = async (
    branding: AdvocateBranding
) => {
    const doc = new jsPDF();
    const marginLeft = 15;
    const pageWidth = 180;
    let y = 20;

    let logoBase64: string | null = null;
    let signatureBase64: string | null = null;

    // Load images
    if (branding.logoUrl) {
        logoBase64 = await loadImageAsBase64(branding.logoUrl);
    }

    if (branding.signatureUrl) {
        signatureBase64 = await loadImageAsBase64(
            branding.signatureUrl
        );
    }

    let qrCodeBase64: string | null = null;

    if (branding.website) {
        qrCodeBase64 = await generateQRCode(branding.website);
    }

    const checkPageBreak = (spaceNeeded = 10) => {
        if (y + spaceNeeded > 280) {
            doc.addPage();
            y = 20;
        }
    };

    const addTitle = (title: string) => {
        checkPageBreak();
        doc.setFont("Times", "Bold");
        doc.setFontSize(16);
        doc.text(title, 105, y, { align: "center" });
        y += 10;
    };

    const addSectionHeading = (heading: string) => {
        checkPageBreak();
        doc.setFont("Times", "Bold");
        doc.setFontSize(12);
        doc.text(heading, marginLeft, y);
        y += 6;
    };

    const addParagraph = (text: string) => {
        doc.setFont("Times", "Normal");
        doc.setFontSize(11);
        const lines = doc.splitTextToSize(text, pageWidth);

        lines.forEach((line: string) => {
            checkPageBreak(6);
            doc.text(line, marginLeft, y);
            y += 6;
        });
        y += 2;
    };

    const addFooter = () => {
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(9);

        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(
                `Generated by SUITCASE | Page ${i} of ${pageCount}`,
                105,
                290,
                { align: "center" }
            );
        }
    };

    // ================= COVER PAGE =================
    if (logoBase64) {
        doc.addImage(logoBase64, "PNG", 85, 15, 40, 40);
    }

    doc.setFont("Times", "Bold");
    doc.setFontSize(22);
    doc.text("SUITCASE", 105, 70, { align: "center" });

    doc.setFontSize(14);
    doc.text("Court Fee & Case Manager Suite", 105, 80, {
        align: "center",
    });

    doc.setFont("Times", "Normal");
    doc.setFontSize(12);
    doc.text("Combined Legal Documents", 105, 95, {
        align: "center",
    });

    doc.text("Privacy Policy & Terms and Conditions", 105, 105, {
        align: "center",
    });

    doc.text("Prepared By:", 105, 125, { align: "center" });
    doc.text(branding.name, 105, 135, { align: "center" });
    doc.text(
        `Enrollment No.: ${branding.enrollmentNumber}`,
        105,
        145,
        { align: "center" }
    );

    doc.text(`Email: ${branding.email}`, 105, 155, {
        align: "center",
    });

    doc.text(`Phone: ${branding.phone}`, 105, 165, {
        align: "center",
    });

    if (branding.chamberName) {
        doc.text(branding.chamberName, 105, 175, {
            align: "center",
        });
    }

    doc.text(
        `Date: ${new Date().toLocaleDateString()}`,
        105,
        190,
        { align: "center" }
    );

    if (qrCodeBase64) {
        doc.addImage(qrCodeBase64, "PNG", 85, 200, 40, 40);
        doc.setFont("Times", "Normal");
        doc.setFontSize(10);
        doc.text("Scan to Visit Official Website", 105, 245, {
            align: "center",
        });
    }

    doc.addPage();
    y = 20;

    // ================= PRIVACY POLICY =================
    addTitle("PRIVACY POLICY");

    addSectionHeading("1. Developer Information");
    addParagraph(
        `${branding.name}/nEmail: ${branding.email}/nPhone: ${branding.phone}`
    );

    addSectionHeading("2. Information We Collect");
    addParagraph(
        "We collect personal, professional, and technical information to provide and improve our services."
    );

    addSectionHeading("3. Data Security");
    addParagraph(
        "We implement industry-standard measures to safeguard user data."
    );

    addSectionHeading("4. Third-Party Services");
    addParagraph(
        "We may integrate with Supabase, Razorpay, Google Play Services, Amazon Affiliate Program, and eCourts."
    );

    addSectionHeading("5. Contact Information");
    addParagraph(
        `Email: ${branding.email}/nPhone: ${branding.phone}`
    );

    doc.addPage();
    y = 20;

    // ================= TERMS & CONDITIONS =================
    addTitle("TERMS AND CONDITIONS");

    addSectionHeading("1. Use of the Application");
    addParagraph(
        "By using SUITCASE, you agree to comply with these terms."
    );

    addSectionHeading("2. Court Fee Disclaimer");
    addParagraph(
        "Court fee calculations are indicative and subject to confirmation by the concerned courts."
    );

    addSectionHeading("3. Payments and Subscriptions");
    addParagraph(
        "Payments are securely processed via Razorpay."
    );

    addSectionHeading("4. Governing Law");
    addParagraph(
        "These terms are governed by the laws of India, with jurisdiction in Himachal Pradesh."
    );

    // ================= SIGNATURE BLOCK =================
    y += 10;
    checkPageBreak(40);

    doc.setFont("Times", "Bold");
    doc.text("Authorized Signatory", 150, y);
    y += 5;

    if (signatureBase64) {
        doc.addImage(signatureBase64, "PNG", 140, y, 40, 20);
        y += 25;
    }

    doc.setFont("Times", "Normal");
    doc.text(branding.name, 150, y);
    y += 5;
    doc.text(`Advocate (Enrl. No. ${branding.enrollmentNumber})`, 150, y);

    doc.addPage();
    y = 40;

    doc.setFont("Times", "Bold");
    doc.setFontSize(14);
    doc.text("Document Verification", 105, y, { align: "center" });

    y += 10;

    doc.setFont("Times", "Normal");
    doc.setFontSize(11);
    doc.text(
        "Scan the QR code below to verify the authenticity of this document.",
        105,
        y,
        { align: "center", maxWidth: 170 }
    );

    y += 15;

    if (qrCodeBase64) {
        doc.addImage(qrCodeBase64, "PNG", 85, y, 40, 40);
    }

    y += 50;

    doc.text(`Issued By: ${branding.name}`, 105, y, { align: "center" });
    y += 10;
    doc.text(`Enrollment No.: ${branding.enrollmentNumber}`, 105, y, { align: "center" });
    y += 10;
    doc.text(`Date of Issue: ${new Date().toLocaleDateString()}`, 105, y, {
        align: "center",
    });

    // Footer
    addFooter();

    // Save PDF
    doc.save("SUITCASE_Legal_Documents_Branded.pdf");
};


